export const GET_TASKS = "GET_TASKS"
export const ADD_TASK = "ADD_TASK"
export const DELETE_TASK = "REMOVE_TASK"
export const DELETE_TASKS = "REMOVE_TASKS"
export const PENDING = "PENDING"
export const EDIT_TASK = "GET_TASKS"
